<?php

namespace Ens\BookerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsRepository extends EntityRepository
{
	public function getRooms(){
		
		$query = $this->getEntityManager()
            ->createQuery('SELECT r.id,r.name FROM EnsBookerBundle:Rooms r');

		$data = $query->getResult();
		$result = array();
		foreach($data as $key=>$val){
			$result[$val['id']] = array('id'=>$val['id'],'name'=>$val['name']);
		}
		
		return $result;
		
	}
}
